#!/bin/bash
echo "查看shell列表"
cat /etc/shells
echo ""

echo "查看当前使用的Shell"
echo $SHELL
echo ""

echo "更新apt源"
apt update
echo ""

echo "安装git zsh figlet中..."
apt install zsh git figlet tree -y
echo ""

echo "更新apt源"
apt install sudo -y
sudo apt update
sudo apt full-upgrade
sudo apt install rsyslog fail2ban -y
rm -rf /etc/ssh/sshd_config.d/
echo ""

echo "设置sshd_config..."
cat > /etc/ssh/sshd_config << EOF
Port 22
ListenAddress 0.0.0.0
ListenAddress ::
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 30s
PermitRootLogin prohibit-password
PasswordAuthentication no
PermitEmptyPasswords no
StrictModes yes
MaxAuthTries 6
MaxSessions 10
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
KbdInteractiveAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
PrintLastLog yes
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

echo "添加公钥"
echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOzTqT/s3C4xHE3sGwnxBPIzxlzSxaUMXXPPZJ8LhQWW' > ~/.ssh/authorized_keys
echo ""

echo "重启sshd中..."
systemctl restart sshd
echo ""

echo "修改motd"
echo '' > /etc/motd
figlet Sm1rkBoy >> /etc/motd
echo ""

echo "修改系统信息"
echo '#!/bin/sh' > /etc/update-motd.d/10-uname
echo ""

echo '设置默认shell为zsh'
chsh -s /usr/bin/zsh
echo ""

echo '写入环境变量信息'
echo 'export ZDOTDIR=$HOME/.config/zsh'     >> /etc/zsh/zshenv
echo 'export XDG_CONFIG_HOME=$HOME/.config' >> /etc/zsh/zshenv
echo 'export XDG_CACHE_HOME=$HOME/.cache'   >> /etc/zsh/zshenv
echo 'export XDG_DATA_HOME=$HOME/.data'     >> /etc/zsh/zshenv
echo 'export XDG_STATE_HOME=$HOME/.state'   >> /etc/zsh/zshenv
echo ""

git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/zsh/zsh-syntax-highlighting
git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git ~/.config/zsh/zsh-autosuggestions
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/zsh/zsh-powerlevel10k
rm -rf .bash_history .bashrc .local .profile
